services:
  backend:
    build:
      context: .                   # The "Search Area" is the root
      dockerfile: backend/Dockerfile # The "Recipe" is in the folder
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file: .env

  frontend:
    build:
      context: ./frontend          # Frontend usually stays isolated
      dockerfile: Dockerfile
    ports:
      - "5500:80"
    volumes:
      - ./frontend:/usr/share/nginx/html