name: Daily NBA Game Logs Bronze Ingestion

on:
  schedule:
    # 8:00 AM UTC is 4:00 AM EST
    - cron: '0 9 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --no-root --no-interaction

      - name: Run Ingestion
        env:
          BRONZE_URL: ${{ secrets.BRONZE_URL }}
          DATABRICKS_URL: ${{ secrets.DATABRICKS_URL }}
          ETL_TOKEN: ${{ secrets.ETL_TOKEN }}
        run: poetry run python data_eng/daily_ingest.py